// Generated by gencpp from file tcp_interface/RCOMMessage.msg
// DO NOT EDIT!


#ifndef TCP_INTERFACE_MESSAGE_RCOMMESSAGE_H
#define TCP_INTERFACE_MESSAGE_RCOMMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace tcp_interface
{
template <class ContainerAllocator>
struct RCOMMessage_
{
  typedef RCOMMessage_<ContainerAllocator> Type;

  RCOMMessage_()
    : header()
    , robotsender()
    , robotreceiver()
    , value()  {
    }
  RCOMMessage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robotsender(_alloc)
    , robotreceiver(_alloc)
    , value(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robotsender_type;
  _robotsender_type robotsender;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robotreceiver_type;
  _robotreceiver_type robotreceiver;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::tcp_interface::RCOMMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tcp_interface::RCOMMessage_<ContainerAllocator> const> ConstPtr;

}; // struct RCOMMessage_

typedef ::tcp_interface::RCOMMessage_<std::allocator<void> > RCOMMessage;

typedef boost::shared_ptr< ::tcp_interface::RCOMMessage > RCOMMessagePtr;
typedef boost::shared_ptr< ::tcp_interface::RCOMMessage const> RCOMMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tcp_interface::RCOMMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tcp_interface::RCOMMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tcp_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'tcp_interface': ['/home/parallels/catkin_ws/src/tcp_interface/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tcp_interface::RCOMMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tcp_interface::RCOMMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tcp_interface::RCOMMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tcp_interface::RCOMMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tcp_interface::RCOMMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tcp_interface::RCOMMessage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tcp_interface::RCOMMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eade0dbd2c9d3c49dad275602c410b50";
  }

  static const char* value(const ::tcp_interface::RCOMMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeade0dbd2c9d3c49ULL;
  static const uint64_t static_value2 = 0xdad275602c410b50ULL;
};

template<class ContainerAllocator>
struct DataType< ::tcp_interface::RCOMMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tcp_interface/RCOMMessage";
  }

  static const char* value(const ::tcp_interface::RCOMMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tcp_interface::RCOMMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string robotsender\n\
string robotreceiver\n\
string value\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tcp_interface::RCOMMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tcp_interface::RCOMMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robotsender);
      stream.next(m.robotreceiver);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RCOMMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tcp_interface::RCOMMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tcp_interface::RCOMMessage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robotsender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robotsender);
    s << indent << "robotreceiver: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robotreceiver);
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TCP_INTERFACE_MESSAGE_RCOMMESSAGE_H
