// Generated by gencpp from file glocalizer/LocalizerRanges.msg
// DO NOT EDIT!


#ifndef GLOCALIZER_MESSAGE_LOCALIZERRANGES_H
#define GLOCALIZER_MESSAGE_LOCALIZERRANGES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace glocalizer
{
template <class ContainerAllocator>
struct LocalizerRanges_
{
  typedef LocalizerRanges_<ContainerAllocator> Type;

  LocalizerRanges_()
    : header()
    , x()
    , y()
    , dist()  {
    }
  LocalizerRanges_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(_alloc)
    , y(_alloc)
    , dist(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _x_type;
  _x_type x;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _y_type;
  _y_type y;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _dist_type;
  _dist_type dist;




  typedef boost::shared_ptr< ::glocalizer::LocalizerRanges_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::glocalizer::LocalizerRanges_<ContainerAllocator> const> ConstPtr;

}; // struct LocalizerRanges_

typedef ::glocalizer::LocalizerRanges_<std::allocator<void> > LocalizerRanges;

typedef boost::shared_ptr< ::glocalizer::LocalizerRanges > LocalizerRangesPtr;
typedef boost::shared_ptr< ::glocalizer::LocalizerRanges const> LocalizerRangesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::glocalizer::LocalizerRanges_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::glocalizer::LocalizerRanges_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace glocalizer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'glocalizer': ['/home/parallels/catkin_ws/src/glocalizer/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::glocalizer::LocalizerRanges_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::glocalizer::LocalizerRanges_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::glocalizer::LocalizerRanges_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::glocalizer::LocalizerRanges_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::glocalizer::LocalizerRanges_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::glocalizer::LocalizerRanges_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::glocalizer::LocalizerRanges_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5c1a7d0143e45b76a2d7478c756a6fe";
  }

  static const char* value(const ::glocalizer::LocalizerRanges_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5c1a7d0143e45b7ULL;
  static const uint64_t static_value2 = 0x6a2d7478c756a6feULL;
};

template<class ContainerAllocator>
struct DataType< ::glocalizer::LocalizerRanges_<ContainerAllocator> >
{
  static const char* value()
  {
    return "glocalizer/LocalizerRanges";
  }

  static const char* value(const ::glocalizer::LocalizerRanges_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::glocalizer::LocalizerRanges_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
float32[] x\n\
float32[] y\n\
float32[] dist\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::glocalizer::LocalizerRanges_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::glocalizer::LocalizerRanges_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.dist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct LocalizerRanges_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::glocalizer::LocalizerRanges_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::glocalizer::LocalizerRanges_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "dist[]" << std::endl;
    for (size_t i = 0; i < v.dist.size(); ++i)
    {
      s << indent << "  dist[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.dist[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GLOCALIZER_MESSAGE_LOCALIZERRANGES_H
