# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from laser_analysis/LaserObstacle.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class LaserObstacle(genpy.Message):
  _md5sum = "ee9cd1755859dc1d90f8adb4433b5b03"
  _type = "laser_analysis/LaserObstacle"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """time stamp
int32 npoints
float64 mindist
float64 y1
float64 y2



"""
  __slots__ = ['stamp','npoints','mindist','y1','y2']
  _slot_types = ['time','int32','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,npoints,mindist,y1,y2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LaserObstacle, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.npoints is None:
        self.npoints = 0
      if self.mindist is None:
        self.mindist = 0.
      if self.y1 is None:
        self.y1 = 0.
      if self.y2 is None:
        self.y2 = 0.
    else:
      self.stamp = genpy.Time()
      self.npoints = 0
      self.mindist = 0.
      self.y1 = 0.
      self.y2 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2Ii3d.pack(_x.stamp.secs, _x.stamp.nsecs, _x.npoints, _x.mindist, _x.y1, _x.y2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.stamp.secs, _x.stamp.nsecs, _x.npoints, _x.mindist, _x.y1, _x.y2,) = _struct_2Ii3d.unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2Ii3d.pack(_x.stamp.secs, _x.stamp.nsecs, _x.npoints, _x.mindist, _x.y1, _x.y2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.stamp.secs, _x.stamp.nsecs, _x.npoints, _x.mindist, _x.y1, _x.y2,) = _struct_2Ii3d.unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2Ii3d = struct.Struct("<2Ii3d")
