; Auto-generated. Do not edit!


(cl:in-package rococo_navigation-msg)


;//! \htmlinclude FollowPersonFeedback.msg.html

(cl:defclass <FollowPersonFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type cl:string
    :initform ""))
)

(cl:defclass FollowPersonFeedback (<FollowPersonFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowPersonFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowPersonFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rococo_navigation-msg:<FollowPersonFeedback> is deprecated: use rococo_navigation-msg:FollowPersonFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <FollowPersonFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rococo_navigation-msg:feedback-val is deprecated.  Use rococo_navigation-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowPersonFeedback>) ostream)
  "Serializes a message object of type '<FollowPersonFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'feedback))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'feedback))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowPersonFeedback>) istream)
  "Deserializes a message object of type '<FollowPersonFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'feedback) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'feedback) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowPersonFeedback>)))
  "Returns string type for a message object of type '<FollowPersonFeedback>"
  "rococo_navigation/FollowPersonFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowPersonFeedback)))
  "Returns string type for a message object of type 'FollowPersonFeedback"
  "rococo_navigation/FollowPersonFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowPersonFeedback>)))
  "Returns md5sum for a message object of type '<FollowPersonFeedback>"
  "c14cdf907e5c7c7fd47292add15660f0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowPersonFeedback)))
  "Returns md5sum for a message object of type 'FollowPersonFeedback"
  "c14cdf907e5c7c7fd47292add15660f0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowPersonFeedback>)))
  "Returns full string definition for message of type '<FollowPersonFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%string feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowPersonFeedback)))
  "Returns full string definition for message of type 'FollowPersonFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%string feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowPersonFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'feedback))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowPersonFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowPersonFeedback
    (cl:cons ':feedback (feedback msg))
))
