// Generated by gencpp from file pnp_msgs/PNPConditionResponse.msg
// DO NOT EDIT!


#ifndef PNP_MSGS_MESSAGE_PNPCONDITIONRESPONSE_H
#define PNP_MSGS_MESSAGE_PNPCONDITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pnp_msgs
{
template <class ContainerAllocator>
struct PNPConditionResponse_
{
  typedef PNPConditionResponse_<ContainerAllocator> Type;

  PNPConditionResponse_()
    : truth_value(0)  {
    }
  PNPConditionResponse_(const ContainerAllocator& _alloc)
    : truth_value(0)  {
    }



   typedef int8_t _truth_value_type;
  _truth_value_type truth_value;




  typedef boost::shared_ptr< ::pnp_msgs::PNPConditionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pnp_msgs::PNPConditionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PNPConditionResponse_

typedef ::pnp_msgs::PNPConditionResponse_<std::allocator<void> > PNPConditionResponse;

typedef boost::shared_ptr< ::pnp_msgs::PNPConditionResponse > PNPConditionResponsePtr;
typedef boost::shared_ptr< ::pnp_msgs::PNPConditionResponse const> PNPConditionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pnp_msgs::PNPConditionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pnp_msgs::PNPConditionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pnp_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'pnp_msgs': ['/home/parallels/catkin_ws/src/pnp_msgs/msg', '/home/parallels/catkin_ws/devel/share/pnp_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pnp_msgs::PNPConditionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pnp_msgs::PNPConditionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pnp_msgs::PNPConditionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pnp_msgs::PNPConditionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pnp_msgs::PNPConditionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pnp_msgs::PNPConditionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pnp_msgs::PNPConditionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ccfd81cc49add05d2909fac38ce1665";
  }

  static const char* value(const ::pnp_msgs::PNPConditionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ccfd81cc49add05ULL;
  static const uint64_t static_value2 = 0xd2909fac38ce1665ULL;
};

template<class ContainerAllocator>
struct DataType< ::pnp_msgs::PNPConditionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pnp_msgs/PNPConditionResponse";
  }

  static const char* value(const ::pnp_msgs::PNPConditionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pnp_msgs::PNPConditionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 truth_value\n\
\n\
";
  }

  static const char* value(const ::pnp_msgs::PNPConditionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pnp_msgs::PNPConditionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.truth_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PNPConditionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pnp_msgs::PNPConditionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pnp_msgs::PNPConditionResponse_<ContainerAllocator>& v)
  {
    s << indent << "truth_value: ";
    Printer<int8_t>::stream(s, indent + "  ", v.truth_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PNP_MSGS_MESSAGE_PNPCONDITIONRESPONSE_H
