// Generated by gencpp from file pnp_msgs/PNPGetVariableValue.msg
// DO NOT EDIT!


#ifndef PNP_MSGS_MESSAGE_PNPGETVARIABLEVALUE_H
#define PNP_MSGS_MESSAGE_PNPGETVARIABLEVALUE_H

#include <ros/service_traits.h>


#include <pnp_msgs/PNPGetVariableValueRequest.h>
#include <pnp_msgs/PNPGetVariableValueResponse.h>


namespace pnp_msgs
{

struct PNPGetVariableValue
{

typedef PNPGetVariableValueRequest Request;
typedef PNPGetVariableValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PNPGetVariableValue
} // namespace pnp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pnp_msgs::PNPGetVariableValue > {
  static const char* value()
  {
    return "2cb822bc826e5843de6b96ba6e683d4b";
  }

  static const char* value(const ::pnp_msgs::PNPGetVariableValue&) { return value(); }
};

template<>
struct DataType< ::pnp_msgs::PNPGetVariableValue > {
  static const char* value()
  {
    return "pnp_msgs/PNPGetVariableValue";
  }

  static const char* value(const ::pnp_msgs::PNPGetVariableValue&) { return value(); }
};


// service_traits::MD5Sum< ::pnp_msgs::PNPGetVariableValueRequest> should match 
// service_traits::MD5Sum< ::pnp_msgs::PNPGetVariableValue > 
template<>
struct MD5Sum< ::pnp_msgs::PNPGetVariableValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pnp_msgs::PNPGetVariableValue >::value();
  }
  static const char* value(const ::pnp_msgs::PNPGetVariableValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pnp_msgs::PNPGetVariableValueRequest> should match 
// service_traits::DataType< ::pnp_msgs::PNPGetVariableValue > 
template<>
struct DataType< ::pnp_msgs::PNPGetVariableValueRequest>
{
  static const char* value()
  {
    return DataType< ::pnp_msgs::PNPGetVariableValue >::value();
  }
  static const char* value(const ::pnp_msgs::PNPGetVariableValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pnp_msgs::PNPGetVariableValueResponse> should match 
// service_traits::MD5Sum< ::pnp_msgs::PNPGetVariableValue > 
template<>
struct MD5Sum< ::pnp_msgs::PNPGetVariableValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pnp_msgs::PNPGetVariableValue >::value();
  }
  static const char* value(const ::pnp_msgs::PNPGetVariableValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pnp_msgs::PNPGetVariableValueResponse> should match 
// service_traits::DataType< ::pnp_msgs::PNPGetVariableValue > 
template<>
struct DataType< ::pnp_msgs::PNPGetVariableValueResponse>
{
  static const char* value()
  {
    return DataType< ::pnp_msgs::PNPGetVariableValue >::value();
  }
  static const char* value(const ::pnp_msgs::PNPGetVariableValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PNP_MSGS_MESSAGE_PNPGETVARIABLEVALUE_H
