// Generated by gencpp from file pnp_msgs/PNPLastEvent.msg
// DO NOT EDIT!


#ifndef PNP_MSGS_MESSAGE_PNPLASTEVENT_H
#define PNP_MSGS_MESSAGE_PNPLASTEVENT_H

#include <ros/service_traits.h>


#include <pnp_msgs/PNPLastEventRequest.h>
#include <pnp_msgs/PNPLastEventResponse.h>


namespace pnp_msgs
{

struct PNPLastEvent
{

typedef PNPLastEventRequest Request;
typedef PNPLastEventResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PNPLastEvent
} // namespace pnp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pnp_msgs::PNPLastEvent > {
  static const char* value()
  {
    return "0acea5ee5ed25bf28c97c4f649046fed";
  }

  static const char* value(const ::pnp_msgs::PNPLastEvent&) { return value(); }
};

template<>
struct DataType< ::pnp_msgs::PNPLastEvent > {
  static const char* value()
  {
    return "pnp_msgs/PNPLastEvent";
  }

  static const char* value(const ::pnp_msgs::PNPLastEvent&) { return value(); }
};


// service_traits::MD5Sum< ::pnp_msgs::PNPLastEventRequest> should match 
// service_traits::MD5Sum< ::pnp_msgs::PNPLastEvent > 
template<>
struct MD5Sum< ::pnp_msgs::PNPLastEventRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pnp_msgs::PNPLastEvent >::value();
  }
  static const char* value(const ::pnp_msgs::PNPLastEventRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pnp_msgs::PNPLastEventRequest> should match 
// service_traits::DataType< ::pnp_msgs::PNPLastEvent > 
template<>
struct DataType< ::pnp_msgs::PNPLastEventRequest>
{
  static const char* value()
  {
    return DataType< ::pnp_msgs::PNPLastEvent >::value();
  }
  static const char* value(const ::pnp_msgs::PNPLastEventRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pnp_msgs::PNPLastEventResponse> should match 
// service_traits::MD5Sum< ::pnp_msgs::PNPLastEvent > 
template<>
struct MD5Sum< ::pnp_msgs::PNPLastEventResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pnp_msgs::PNPLastEvent >::value();
  }
  static const char* value(const ::pnp_msgs::PNPLastEventResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pnp_msgs::PNPLastEventResponse> should match 
// service_traits::DataType< ::pnp_msgs::PNPLastEvent > 
template<>
struct DataType< ::pnp_msgs::PNPLastEventResponse>
{
  static const char* value()
  {
    return DataType< ::pnp_msgs::PNPLastEvent >::value();
  }
  static const char* value(const ::pnp_msgs::PNPLastEventResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PNP_MSGS_MESSAGE_PNPLASTEVENT_H
