// Generated by gencpp from file pnp_msgs/PNPReward.msg
// DO NOT EDIT!


#ifndef PNP_MSGS_MESSAGE_PNPREWARD_H
#define PNP_MSGS_MESSAGE_PNPREWARD_H

#include <ros/service_traits.h>


#include <pnp_msgs/PNPRewardRequest.h>
#include <pnp_msgs/PNPRewardResponse.h>


namespace pnp_msgs
{

struct PNPReward
{

typedef PNPRewardRequest Request;
typedef PNPRewardResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PNPReward
} // namespace pnp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pnp_msgs::PNPReward > {
  static const char* value()
  {
    return "d6bac371d18603a2d7685bb5dacec7cb";
  }

  static const char* value(const ::pnp_msgs::PNPReward&) { return value(); }
};

template<>
struct DataType< ::pnp_msgs::PNPReward > {
  static const char* value()
  {
    return "pnp_msgs/PNPReward";
  }

  static const char* value(const ::pnp_msgs::PNPReward&) { return value(); }
};


// service_traits::MD5Sum< ::pnp_msgs::PNPRewardRequest> should match 
// service_traits::MD5Sum< ::pnp_msgs::PNPReward > 
template<>
struct MD5Sum< ::pnp_msgs::PNPRewardRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pnp_msgs::PNPReward >::value();
  }
  static const char* value(const ::pnp_msgs::PNPRewardRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pnp_msgs::PNPRewardRequest> should match 
// service_traits::DataType< ::pnp_msgs::PNPReward > 
template<>
struct DataType< ::pnp_msgs::PNPRewardRequest>
{
  static const char* value()
  {
    return DataType< ::pnp_msgs::PNPReward >::value();
  }
  static const char* value(const ::pnp_msgs::PNPRewardRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pnp_msgs::PNPRewardResponse> should match 
// service_traits::MD5Sum< ::pnp_msgs::PNPReward > 
template<>
struct MD5Sum< ::pnp_msgs::PNPRewardResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pnp_msgs::PNPReward >::value();
  }
  static const char* value(const ::pnp_msgs::PNPRewardResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pnp_msgs::PNPRewardResponse> should match 
// service_traits::DataType< ::pnp_msgs::PNPReward > 
template<>
struct DataType< ::pnp_msgs::PNPRewardResponse>
{
  static const char* value()
  {
    return DataType< ::pnp_msgs::PNPReward >::value();
  }
  static const char* value(const ::pnp_msgs::PNPRewardResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PNP_MSGS_MESSAGE_PNPREWARD_H
