// Generated by gencpp from file pnp_msgs/PNPRewardResponse.msg
// DO NOT EDIT!


#ifndef PNP_MSGS_MESSAGE_PNPREWARDRESPONSE_H
#define PNP_MSGS_MESSAGE_PNPREWARDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pnp_msgs
{
template <class ContainerAllocator>
struct PNPRewardResponse_
{
  typedef PNPRewardResponse_<ContainerAllocator> Type;

  PNPRewardResponse_()
    : reward(0.0)  {
    }
  PNPRewardResponse_(const ContainerAllocator& _alloc)
    : reward(0.0)  {
    }



   typedef float _reward_type;
  _reward_type reward;




  typedef boost::shared_ptr< ::pnp_msgs::PNPRewardResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pnp_msgs::PNPRewardResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PNPRewardResponse_

typedef ::pnp_msgs::PNPRewardResponse_<std::allocator<void> > PNPRewardResponse;

typedef boost::shared_ptr< ::pnp_msgs::PNPRewardResponse > PNPRewardResponsePtr;
typedef boost::shared_ptr< ::pnp_msgs::PNPRewardResponse const> PNPRewardResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pnp_msgs::PNPRewardResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pnp_msgs::PNPRewardResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pnp_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'pnp_msgs': ['/home/parallels/catkin_ws/src/pnp_msgs/msg', '/home/parallels/catkin_ws/devel/share/pnp_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pnp_msgs::PNPRewardResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pnp_msgs::PNPRewardResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pnp_msgs::PNPRewardResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pnp_msgs::PNPRewardResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pnp_msgs::PNPRewardResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pnp_msgs::PNPRewardResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pnp_msgs::PNPRewardResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c5a2bbc277e822b80ec2fb352dd1efe";
  }

  static const char* value(const ::pnp_msgs::PNPRewardResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c5a2bbc277e822bULL;
  static const uint64_t static_value2 = 0x80ec2fb352dd1efeULL;
};

template<class ContainerAllocator>
struct DataType< ::pnp_msgs::PNPRewardResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pnp_msgs/PNPRewardResponse";
  }

  static const char* value(const ::pnp_msgs::PNPRewardResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pnp_msgs::PNPRewardResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 reward\n\
\n\
";
  }

  static const char* value(const ::pnp_msgs::PNPRewardResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pnp_msgs::PNPRewardResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reward);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PNPRewardResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pnp_msgs::PNPRewardResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pnp_msgs::PNPRewardResponse_<ContainerAllocator>& v)
  {
    s << indent << "reward: ";
    Printer<float>::stream(s, indent + "  ", v.reward);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PNP_MSGS_MESSAGE_PNPREWARDRESPONSE_H
