// Generated by gencpp from file pnp_msgs/PNPSetVariableValue.msg
// DO NOT EDIT!


#ifndef PNP_MSGS_MESSAGE_PNPSETVARIABLEVALUE_H
#define PNP_MSGS_MESSAGE_PNPSETVARIABLEVALUE_H

#include <ros/service_traits.h>


#include <pnp_msgs/PNPSetVariableValueRequest.h>
#include <pnp_msgs/PNPSetVariableValueResponse.h>


namespace pnp_msgs
{

struct PNPSetVariableValue
{

typedef PNPSetVariableValueRequest Request;
typedef PNPSetVariableValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PNPSetVariableValue
} // namespace pnp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pnp_msgs::PNPSetVariableValue > {
  static const char* value()
  {
    return "f26fb17f1178850596cc513f7a908898";
  }

  static const char* value(const ::pnp_msgs::PNPSetVariableValue&) { return value(); }
};

template<>
struct DataType< ::pnp_msgs::PNPSetVariableValue > {
  static const char* value()
  {
    return "pnp_msgs/PNPSetVariableValue";
  }

  static const char* value(const ::pnp_msgs::PNPSetVariableValue&) { return value(); }
};


// service_traits::MD5Sum< ::pnp_msgs::PNPSetVariableValueRequest> should match 
// service_traits::MD5Sum< ::pnp_msgs::PNPSetVariableValue > 
template<>
struct MD5Sum< ::pnp_msgs::PNPSetVariableValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pnp_msgs::PNPSetVariableValue >::value();
  }
  static const char* value(const ::pnp_msgs::PNPSetVariableValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pnp_msgs::PNPSetVariableValueRequest> should match 
// service_traits::DataType< ::pnp_msgs::PNPSetVariableValue > 
template<>
struct DataType< ::pnp_msgs::PNPSetVariableValueRequest>
{
  static const char* value()
  {
    return DataType< ::pnp_msgs::PNPSetVariableValue >::value();
  }
  static const char* value(const ::pnp_msgs::PNPSetVariableValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pnp_msgs::PNPSetVariableValueResponse> should match 
// service_traits::MD5Sum< ::pnp_msgs::PNPSetVariableValue > 
template<>
struct MD5Sum< ::pnp_msgs::PNPSetVariableValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pnp_msgs::PNPSetVariableValue >::value();
  }
  static const char* value(const ::pnp_msgs::PNPSetVariableValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pnp_msgs::PNPSetVariableValueResponse> should match 
// service_traits::DataType< ::pnp_msgs::PNPSetVariableValue > 
template<>
struct DataType< ::pnp_msgs::PNPSetVariableValueResponse>
{
  static const char* value()
  {
    return DataType< ::pnp_msgs::PNPSetVariableValue >::value();
  }
  static const char* value(const ::pnp_msgs::PNPSetVariableValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PNP_MSGS_MESSAGE_PNPSETVARIABLEVALUE_H
