// Generated by gencpp from file rococo_navigation/FollowCorridorActionGoal.msg
// DO NOT EDIT!


#ifndef ROCOCO_NAVIGATION_MESSAGE_FOLLOWCORRIDORACTIONGOAL_H
#define ROCOCO_NAVIGATION_MESSAGE_FOLLOWCORRIDORACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <rococo_navigation/FollowCorridorGoal.h>

namespace rococo_navigation
{
template <class ContainerAllocator>
struct FollowCorridorActionGoal_
{
  typedef FollowCorridorActionGoal_<ContainerAllocator> Type;

  FollowCorridorActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  FollowCorridorActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::rococo_navigation::FollowCorridorGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FollowCorridorActionGoal_

typedef ::rococo_navigation::FollowCorridorActionGoal_<std::allocator<void> > FollowCorridorActionGoal;

typedef boost::shared_ptr< ::rococo_navigation::FollowCorridorActionGoal > FollowCorridorActionGoalPtr;
typedef boost::shared_ptr< ::rococo_navigation::FollowCorridorActionGoal const> FollowCorridorActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rococo_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rococo_navigation': ['/home/parallels/catkin_ws/devel/share/rococo_navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58b3c34719aac7352eb6cbb6451aa712";
  }

  static const char* value(const ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58b3c34719aac735ULL;
  static const uint64_t static_value2 = 0x2eb6cbb6451aa712ULL;
};

template<class ContainerAllocator>
struct DataType< ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rococo_navigation/FollowCorridorActionGoal";
  }

  static const char* value(const ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
FollowCorridorGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: rococo_navigation/FollowCorridorGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Goal\n\
# target position \n\
float32 target_X\n\
float32 target_Y\n\
# max velocity [m/s]\n\
float32 max_vel\n\
";
  }

  static const char* value(const ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct FollowCorridorActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rococo_navigation::FollowCorridorActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::rococo_navigation::FollowCorridorGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROCOCO_NAVIGATION_MESSAGE_FOLLOWCORRIDORACTIONGOAL_H
