// Generated by gencpp from file rococo_navigation/TurnGoal.msg
// DO NOT EDIT!


#ifndef ROCOCO_NAVIGATION_MESSAGE_TURNGOAL_H
#define ROCOCO_NAVIGATION_MESSAGE_TURNGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rococo_navigation
{
template <class ContainerAllocator>
struct TurnGoal_
{
  typedef TurnGoal_<ContainerAllocator> Type;

  TurnGoal_()
    : target_angle(0.0)
    , absolute_relative_flag()
    , max_ang_vel(0.0)  {
    }
  TurnGoal_(const ContainerAllocator& _alloc)
    : target_angle(0.0)
    , absolute_relative_flag(_alloc)
    , max_ang_vel(0.0)  {
    }



   typedef float _target_angle_type;
  _target_angle_type target_angle;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _absolute_relative_flag_type;
  _absolute_relative_flag_type absolute_relative_flag;

   typedef float _max_ang_vel_type;
  _max_ang_vel_type max_ang_vel;




  typedef boost::shared_ptr< ::rococo_navigation::TurnGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rococo_navigation::TurnGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TurnGoal_

typedef ::rococo_navigation::TurnGoal_<std::allocator<void> > TurnGoal;

typedef boost::shared_ptr< ::rococo_navigation::TurnGoal > TurnGoalPtr;
typedef boost::shared_ptr< ::rococo_navigation::TurnGoal const> TurnGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rococo_navigation::TurnGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rococo_navigation::TurnGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rococo_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rococo_navigation': ['/home/parallels/catkin_ws/devel/share/rococo_navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rococo_navigation::TurnGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rococo_navigation::TurnGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rococo_navigation::TurnGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rococo_navigation::TurnGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rococo_navigation::TurnGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rococo_navigation::TurnGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rococo_navigation::TurnGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6590b572f5a90e57b737335d6531bce7";
  }

  static const char* value(const ::rococo_navigation::TurnGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6590b572f5a90e57ULL;
  static const uint64_t static_value2 = 0xb737335d6531bce7ULL;
};

template<class ContainerAllocator>
struct DataType< ::rococo_navigation::TurnGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rococo_navigation/TurnGoal";
  }

  static const char* value(const ::rococo_navigation::TurnGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rococo_navigation::TurnGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Goal\n\
# target_angle [DEG] \n\
float32 target_angle\n\
# flag ABS/REL\n\
string absolute_relative_flag\n\
# max angular velocity [DEG/s]\n\
float32 max_ang_vel\n\
";
  }

  static const char* value(const ::rococo_navigation::TurnGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rococo_navigation::TurnGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_angle);
      stream.next(m.absolute_relative_flag);
      stream.next(m.max_ang_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TurnGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rococo_navigation::TurnGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rococo_navigation::TurnGoal_<ContainerAllocator>& v)
  {
    s << indent << "target_angle: ";
    Printer<float>::stream(s, indent + "  ", v.target_angle);
    s << indent << "absolute_relative_flag: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.absolute_relative_flag);
    s << indent << "max_ang_vel: ";
    Printer<float>::stream(s, indent + "  ", v.max_ang_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROCOCO_NAVIGATION_MESSAGE_TURNGOAL_H
